baseURL = "max-amb.github.io"
languageCode = "en-us"
title = "Max's blurtie blog"
author = "Max Ambaum"
enableRobotsTXT = true
theme = "hugo-bearblog"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[markup]
  [markup.highlight]
    style = 'friendly'
    lineNos = true
    lineNumbersInTable = false
    codeFences = true

  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$']]
          inline = [['$', '$']]

[params]
  favicon = "favicon.svg"
  enablePostNavigator = true
  math = true
  DefaultContentLanguage = "en"
  hideMadeWithLine = false

[markup.tableOfContents]
  startLevel = 2
  endLevel = 6
  ordered = false
